# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20160509_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[(0, '男'), (1, '女')], default=0, max_length=10),
        ),
    ]
