# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=30)),
                ('port', models.IntegerField()),
                ('cpu', models.CharField(max_length=30)),
                ('mem', models.CharField(max_length=30)),
                ('disk', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
